version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./data/telephones.json
        target: /root/data/telephones.json
